ERRMOT.LS      Robot Name ROBOT 17-JAN-19 14:31:34  

1" 17-JAN-19 13:15:54 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
2" 17-JAN-19 13:08:02 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
3" 14-JAN-19 08:38:44 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
